Libft: ft_calloc.h	ft_isascii.h ft_memccpy.h ft_memcpy.h ft_strchr.h ft_strlen.h ft_strrchr.h ft_atoi.h ft_isalnum.h ft_isdigit.h ft_memchr.h ft_memmove.h ft_strlcat.h ft_strncmp.h ft_tolower.h ft_bzero.c	ft_isalpha.c ft_isprint.h ft_memcmp.h ft_memset.o ft_strlcpy.h ft_strnstr.h ft_toupper.h

identify_chars.o:
